import { test, expect } from '@playwright/test'
test('universe choice preserves index and volume fields save and clear independently', async ({ page }, info) => {
  let saved = { index_name:'NIFTY500', universe_mode:'index', ma_type:'SMMA', length:5, delay:0, offset_sigma:6, alma_offset:.85, pe_filter_operator:'none', volume_min:null, volume_max:null }
  await page.route('**/api/session', route => route.fulfill({ json:{ connected:true } }))
  await page.route('**/api/scanner/config', async route => {
    if (route.request().method() === 'POST') saved = route.request().postDataJSON()
    await route.fulfill({ json:saved })
  })
  await page.request.post('/api/login',{data:{username:'fixture-user',password:'fixture-password'}})
 await page.goto('/')
  if (info.project.name === 'mobile') await page.getByRole('button',{name:'Open navigation menu'}).click()
  await page.getByRole('button',{name: /Settings/}).click()
  await expandSettings(page)
  const index = page.getByLabel('Market index')
  await expect(index).toHaveValue('NIFTY500')
  await page.getByRole('button',{name:'Full NSE',exact:true}).click()
  await expect(index).toHaveCount(0)
  await page.getByLabel('Exclude volume below').fill('1000')
  await page.getByLabel('Exclude volume above').fill('5000')
  await page.getByLabel("Today's volume > 30-day average volume").check()
  await page.getByRole('button',{name:'Save settings'}).click()
  await expect(page.getByText('Settings saved')).toBeVisible()
  expect(saved.universe_mode).toBe('full_nse');expect(saved.index_name).toBe('NIFTY500')
  expect(saved.volume_min).toBe(1000);expect(saved.volume_max).toBe(5000);expect(saved.volume_above_30d_average).toBe(true)
  await page.getByRole('button',{name:'Index',exact:true}).click()
  await expect(index).toHaveValue('NIFTY500')
  await page.getByLabel('Exclude volume below').fill('')
  await page.getByRole('button',{name:'Save settings'}).click()
  await expect.poll(()=>saved.volume_min).toBeNull()
  expect(saved.volume_max).toBe(5000)
})

test('confirmed 3D is separate, persists and does not enable trading', async ({ page }, info) => {
 let saved={index_name:'NIFTY500',universe_mode:'index',ma_type:'SMMA',length:5,delay:0,offset_sigma:6,alma_offset:.85,pe_filter_operator:'none',use_alternate_resolution:true,alternate_multiplier:3,alternate_mode:'comparison'}
 const enableRequests=[]
 page.on('request',r=>{if(r.url().includes('/api/autotrade/enable'))enableRequests.push(r.url())})
 await page.route('**/api/session',r=>r.fulfill({json:{connected:true}}))
 await page.route('**/api/scanner/config',r=>{if(r.request().method()==='POST')saved=r.request().postDataJSON();return r.fulfill({json:saved})})
 await page.request.post('/api/login',{data:{username:'fixture-user',password:'fixture-password'}})
 await page.goto('/')
 if(info.project.name==='mobile')await page.getByRole('button',{name:'Open navigation menu'}).click()
 await page.getByRole('button',{name:/Settings/}).click()
  await expandSettings(page)
 await expect(page.getByLabel('3D mode',{exact:true})).toHaveValue('comparison')
 await page.getByLabel('3D mode',{exact:true}).selectOption('confirmed')
 await page.getByRole('button',{name:'Save settings'}).click()
 await expect.poll(()=>saved.alternate_mode).toBe('confirmed')
 await expect(page.getByText('Settings saved')).toBeVisible()
 expect(enableRequests).toEqual([])
 await page.getByLabel('3D mode',{exact:true}).scrollIntoViewIfNeeded()
 await page.screenshot({path:`/tmp/confirmed-settings-${info.project.name}.jpg`,type:'jpeg',quality:65,scale:'css'})
 await page.reload()
 if(info.project.name==='mobile')await page.getByRole('button',{name:'Open navigation menu'}).click()
 await page.getByRole('button',{name:/Settings/}).click()
  await expandSettings(page)
 await expect(page.getByLabel('3D mode',{exact:true})).toHaveValue('confirmed')
 await page.getByLabel('3D mode',{exact:true}).selectOption('comparison')
 await page.getByRole('button',{name:'Save settings'}).click()
 await expect.poll(()=>saved.alternate_mode).toBe('comparison')
})

test('52W range saves and collapsing sections preserves entered values', async ({page},info)=>{
  let config={index_name:'NIFTY500',universe_mode:'index',ma_type:'SMMA',length:5,delay:0,offset_sigma:6,alma_offset:.85,pe_filter_operator:'none'}
  await page.route('**/api/scanner/config',r=>{if(r.request().method()==='POST')config=r.request().postDataJSON();return r.fulfill({json:config})})
  await page.request.post('/api/login',{data:{username:'fixture-user',password:'fixture-password'}})
  await page.goto('/')
  if(info.project.name==='mobile')await page.getByRole('button',{name:'Open navigation menu'}).click()
  await page.getByRole('button',{name:/Settings/}).click()
  await expandSettings(page)
  await page.getByLabel('Min distance from 52W high %').fill('10')
  await page.getByLabel('Max distance from 52W high %').fill('20')
  const summary=page.locator('summary').filter({hasText:'Fundamental filters'})
  await summary.click()
  await expect(page.getByLabel('Min distance from 52W high %')).toBeHidden()
  await page.getByRole('button',{name:'Save settings'}).click()
  await expect.poll(()=>config.min_52w_high_distance_pct).toBe(10)
  expect(config.max_52w_high_distance_pct).toBe(20)
  await summary.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByLabel('Min distance from 52W high %')).toHaveValue('10')
  await page.getByLabel('Min distance from 52W high %').fill('')
  await page.getByRole('button',{name:'Save settings'}).click()
  await expect.poll(()=>config.min_52w_high_distance_pct).toBeNull()
  await page.screenshot({path:info.outputPath('expandable-settings.png'),fullPage:true})
})

async function expandSettings(page) {
  const sections = page.locator('.settings-disclosure')
  await expect(sections).toHaveCount(6)
  await expect(page.locator('.settings-disclosure[open]')).toHaveCount(0)
  for (const summary of await page.locator('.settings-disclosure > summary').all()) await summary.click()
}
