import {test,expect} from '@playwright/test'
test('Search research is separate, overlays toggle, and weights only save to Search',async({page},info)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message))
 const mutations=[];page.on('request',r=>{if(r.method()==='POST')mutations.push(new URL(r.url()).pathname)})
 const bars=Array.from({length:40},(_,i)=>({date:new Date(Date.UTC(2026,6,1+i)).toISOString().slice(0,10),open:100+i,high:105+i,low:98+i,close:102+i,volume:1000,supertrend_value:96+i,direction:-1,bullFlip:i===4,bearFlip:false}))
 const weights={long:{ROE:[100,0,20]},short:{RSI:[100,30,70]}}
 const scores={long:{value:75,coverage:100,components:[{name:'ROE',value:15,weight:100,points:75}]},short:{value:50,coverage:100,components:[{name:'RSI',value:50,weight:100,points:50}]}}
 await page.route('**/api/search/symbols?*',r=>r.fulfill({json:{results:[{symbol:'TEST',name:'Test Company'}]}}))
 await page.route('**/api/search/TEST',r=>r.fulfill({json:{symbol:'TEST',as_of:bars.at(-1).date,fundamentals_as_of:'2026-09-10',bars,occ:bars.map(b=>({date:b.date,open_series:b.open,close_series:b.close,buy:false,exit:false})),occ_mode:'1D',weights,scores,warnings:[],fields:{'Stock P/E':{value:20,status:'SUCCESS',source:'provider'},'PEG Ratio':{value:null,status:'UNAVAILABLE',source:'provider'}}}}))
 await page.route('**/api/search/weights',r=>r.fulfill({json:r.request().postDataJSON()}))
 await page.request.post('/api/login',{data:{username:'fixture-user',password:'fixture-password'}})
 await page.goto('/')
 if(info.project.name==='mobile')await page.getByRole('button',{name:'Open navigation menu'}).click()
 await page.getByRole('button',{name:/Search/}).click()
 await page.getByLabel('Search NSE stocks').fill('TEST')
 await page.getByRole('button',{name:'TEST · Test Company'}).click()
 await expect(page.getByRole('img',{name:'TEST research candlestick chart'})).toBeVisible()
 await expect(page.locator('.search-ratios')).toContainText('UNAVAILABLE')
 if(info.project.name==='mobile')expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
 await page.getByRole('button',{name:/Supertrend \(10, 3\)/}).click();await expect(page.getByRole('button',{name:/OCC \(1D\)/})).toHaveAttribute('aria-pressed','true')
 await page.getByRole('button',{name:'10Yr',exact:true}).click()
 await page.locator('summary').filter({hasText:'Research weights and thresholds'}).click()
 await page.getByLabel('ROE · Weight').fill('80')
 await page.getByRole('button',{name:'Save research weights'}).click()
 await expect(page.getByText('Research weights saved. Trading settings are unchanged.')).toBeVisible()
 expect(mutations).toEqual(['/api/search/weights'])
 expect(errors).toEqual([])
 await page.screenshot({path:info.outputPath('search.png'),fullPage:true})
})
