import {useEffect,useState} from 'react'

export function BrokerAccountNotice({api,alwaysShow=false}) {
 const [data,setData]=useState(null),[phrase,setPhrase]=useState(''),[account,setAccount]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function load(){try{const next=await api('/api/broker-account');setData(next);setError('');setAccount(value=>value||next.account_id||'')}catch(e){setError(e.message)}}
 useEffect(()=>{load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[])
 if(!data || (!alwaysShow&&!data.error&&!data.legacy.total))return error?<p role="alert">{error}</p>:null
 async function bind(){setBusy(true);setError('');try{setData(await api('/api/broker-account/bind-legacy',{method:'POST',body:JSON.stringify({account_id:account,confirm_phrase:phrase})}));setPhrase('')}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="live-gate" aria-label="Broker account safety"><strong>{alwaysShow ? "Broker account ownership" : "Broker account safety — trading paused"}</strong>{alwaysShow&&<><p>Recorded account: {data.account_id||"Not established"}</p><p>No legacy records awaiting confirmation does not mean trading is enabled or all risk checks have passed.</p><p>Risk last checked: {data.risk_checked_at||"Not checked yet"}</p>{data.risk_history_error&&<p role="alert" className="loss">BUYs blocked: {data.risk_history_error}</p>}<button className="secondary-button" type="button" onClick={load}>Refresh account status</button><p>{data.legacy.total ? "Ownership confirmation required. Live trading remains paused." : data.error ? "Account verification needs attention." : "No legacy records await ownership confirmation."}</p></>}{data.error&&<p role="alert" className="loss">{data.error}</p>}{data.legacy.total>0&&<><p>{data.legacy.total} legacy position/order/GTT records have no verified account owner. Compare these records with your Kite trade history before confirming. This action assigns ownership only; it does not change trades, reset P&amp;L, enable trading or place orders.</p><p>Recorded workspace account: {data.account_id||'Not established'}. The connected account must match.</p><details><summary>Review legacy records before confirming</summary><div className="table-wrap"><table className="signal-table"><thead><tr><th>Record</th><th>Symbol</th><th>Quantity</th><th>Broker reference</th><th>Status</th></tr></thead><tbody>{data.legacy_records?.map(r=><tr key={`${r.kind}-${r.id}`}><td>{r.kind} #{r.id}</td><td>{r.symbol}</td><td>{r.quantity??'—'}</td><td>{r.broker_ref||'None recorded'}</td><td>{r.status}</td></tr>)}</tbody></table></div></details><label>Verified legacy account ID<input aria-label="Verified legacy account ID" value={account} onChange={e=>setAccount(e.target.value.trim())}/></label><label>Ownership confirmation<input aria-label="Legacy ownership confirmation" placeholder={`BIND LEGACY RECORDS TO ${account}`} value={phrase} onChange={e=>setPhrase(e.target.value)}/></label><button className="secondary-button" disabled={busy||!account||phrase!==`BIND LEGACY RECORDS TO ${account}`} onClick={bind}>Confirm legacy ownership</button></>}{error&&<p role="alert">{error}</p>}</section>
}

export function BrokerAccountSwitch({api,change,onResolved}) {
 const [phrase,setPhrase]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const blocked=change.legacy>0||Object.values(change.blockers||{}).some(Boolean)
 async function resolve(action){setBusy(true);setError('');try{await api('/api/broker-account/switch',{method:'POST',body:JSON.stringify({action,confirm_phrase:phrase})});await onResolved()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <main className="auth-layout kite-connect-layout"><section className="auth-panel"><div className="panel-topline"><span>Account safety</span><span>Trading paused</span></div><h2>Broker account changed</h2><p>Existing workspace: <strong>{change.from_account}</strong>. New OAuth account: <strong>{change.to_account}</strong>.</p><p>The original Kite connection has been retained. Historical records will never be reassigned to the new account.</p>{blocked?<p role="alert">Resolve existing positions, orders, GTTs and legacy ownership using the original account first. A different account cannot manage them.</p>:<p>You can explicitly switch because no outstanding exposure remains. Trading stays paused and requires a separately confirmed baseline and live activation.</p>}{change.expired&&<p role="alert">This request expired. Keep the original account, then restart Connect to Kite.</p>}<button className="secondary-button" disabled={busy} onClick={()=>resolve('keep')}>Keep original account</button><label>Account switch confirmation<input aria-label="Account switch confirmation" value={phrase} onChange={e=>setPhrase(e.target.value)} placeholder={`SWITCH BROKER ACCOUNT TO ${change.to_account}`}/></label><button className="primary-button" disabled={busy||blocked||change.expired||phrase!==`SWITCH BROKER ACCOUNT TO ${change.to_account}`} onClick={()=>resolve('switch')}>Confirm account switch</button>{error&&<p role="alert">{error}</p>}</section></main>
}
