import {useEffect, useState} from 'react'

export default function SessionActivity({api}) {
  const [data,setData]=useState(null),[error,setError]=useState('')
  async function refresh() { try {setData(await api('/api/sessions'));setError('')} catch(e) {setError(e.message)} }
  useEffect(()=>{refresh()},[])
  const time=value=>value ? new Date(value).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})+' IST' : 'Not recorded'
  return <section className="settings-section"><h3>Session activity</h3><p className="settings-help">The Kite connection is shared across authenticated dashboard sessions. Starting Kite login blocks that session until its callback succeeds. This is not a second authentication factor.</p><button className="secondary-button" onClick={refresh}>Refresh session activity</button>{error && <p role="alert">{error}</p>}{data && <><p>Latest completed Kite login: {time(data.last_kite_login?.created_at)}{data.last_kite_login && ` · ${data.last_kite_login.ip} · ${data.last_kite_login.user_agent}`}</p><h4>Active dashboard sessions</h4><div className="table-wrap"><table className="signal-table"><thead><tr><th>Session</th><th>IP address</th><th>Device / browser</th><th>Signed in</th><th>Last seen</th><th>Kite login</th></tr></thead><tbody>{data.active_sessions.map(row=><tr key={row.id}><td>{row.current?'This session':'Other session'}</td><td>{row.ip}</td><td>{row.user_agent}</td><td>{time(row.created_at)}</td><td>{time(row.last_seen)}</td><td>{row.kite_pending?'Awaiting completion':'Shared connection available if valid'}</td></tr>)}</tbody></table></div><h4>Recent activity</h4><p className="settings-help">Latest 50 events, retained for 90 days. Device/browser labels are reported by the browser.</p><div className="table-wrap"><table className="signal-table"><thead><tr><th>Event</th><th>Time</th><th>IP address</th><th>Device / browser</th></tr></thead><tbody>{data.recent_logins.map(row=><tr key={row.id}><td>{row.kind.replaceAll('_',' ')}</td><td>{time(row.created_at)}</td><td>{row.ip}</td><td>{row.user_agent}</td></tr>)}</tbody></table></div></>}</section>
}
