import {useEffect,useState} from 'react'
const labels={enabled:'Enable Telegram notifications',orders:'Order submissions, fills and failures',safety:'Kill switch, GTT triggers and missing P&L history',connection:'Kite connection alerts',service:'Backend restart alerts',capacity:'Daily BUY allowance and position capacity',scanner:'Scanner completion summaries',paper:'Include demo order notifications'}
export default function TelegramSettings({api}) {
 const [data,setData]=useState(null),[settings,setSettings]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{let active=true;async function load(){try{const r=await api('/api/telegram');if(active){setData(r);setSettings(s=>s||r.settings)}}catch(e){if(active)setError(e.message)}}load();const timer=setInterval(load,5000);return()=>{active=false;clearInterval(timer)}},[])
 async function save(e){e.preventDefault();setBusy(true);setError('');try{const r=await api('/api/telegram/settings',{method:'POST',body:JSON.stringify(settings)});setData(r);setSettings(r.settings);setMessage('Notification settings saved.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function test(){setBusy(true);setError('');try{const r=await api('/api/telegram/test',{method:'POST'});setMessage(r.queued?'Test queued. Check delivery status below.':'Not queued. Enable notifications and service alerts, or check queue capacity.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="overview-section"><h3>Telegram notifications</h3><p className="muted">Updates are sent to your configured group. Only your original private Telegram account can use /status and /stopvm in a private chat with the bot. VM deallocation requires a second confirmation within 60 seconds. Delivery failures do not block trading.</p>{error&&<p role="alert" className="error-message">{error}</p>}{!data?<p>Loading Telegram status…</p>:<><p>Private commands: {data.commands?.running?'Running':'Unavailable'} · VM: {data.commands?.vm||'Not configured'}</p>{data.commands?.error&&<p role="status">{data.commands.error}</p>}<p>Credentials: {data.configured?'Configured on server':'Missing TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID'} · Worker: {data.worker_running?'Running':'Stopped'} · Queued: {data.queued}</p><p className="muted">Last successful delivery: {data.last_success?new Date(data.last_success).toLocaleString('en-IN'):'None this service session'} · Sent: {data.sent} · Failed: {data.failed} · Dropped: {data.dropped}</p>{data.last_error&&<p role="status" className="error-message">{data.last_error}</p>}<form onSubmit={save}><div className="settings-grid">{Object.entries(labels).map(([key,label])=><label className="toggle-field" key={key}><input type="checkbox" checked={settings[key]} onChange={e=>setSettings(s=>({...s,[key]:e.target.checked}))}/><span>{label}</span></label>)}</div><div className="trading-actions"><button className="primary-button" disabled={busy}>Save Telegram settings</button><button type="button" className="secondary-button" disabled={busy||!data.configured} onClick={test}>Send test notification</button></div></form>{message&&<p role="status">{message}</p>}<div className="table-wrap"><table className="signal-table"><thead><tr><th>Time</th><th>Event</th><th>Delivery</th><th>Detail</th></tr></thead><tbody>{data.recent.map((r,i)=><tr key={i}><td>{new Date(r.created_at).toLocaleString('en-IN')}</td><td>{r.kind}</td><td>{r.status}</td><td>{r.detail}</td></tr>)}</tbody></table></div></>}</section>
}
